/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Venrar
 */
public class CadastrarVeiculo extends javax.swing.JFrame {

	List<MarcasCadastradas> listaM = new ArrayList<MarcasCadastradas>();
	List<Proprietario> listap = new ArrayList<Proprietario>();
	List<Veiculo> listav = new ArrayList<Veiculo>();
	ExportarImportar ex = new ExportarImportar();
	protected Veiculo veiculo = new Veiculo();
	protected Modelo modelo = new Modelo();
	protected Marca marca = new Marca();

	/**
	 * Creates new form CadastrarVeiculo
	 */
	public CadastrarVeiculo() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		CadastroCor = new javax.swing.JTextField();
		CadastroModelo = new javax.swing.JTextField();
		CadastroMarca = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		CadastroEmail = new javax.swing.JTextField();
		jLabel20 = new javax.swing.JLabel();
		BotaoVoltar = new javax.swing.JButton();
		BotaoCadastrar = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		CadastroPlaca = new javax.swing.JTextField();
		BotaoCadastrarProprietario = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		CadastroCor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CadastroCorActionPerformed(evt);
			}
		});

		CadastroModelo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CadastroModeloActionPerformed(evt);
			}
		});

		CadastroMarca.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CadastroMarcaActionPerformed(evt);
			}
		});

		jLabel17.setText("Marca:");

		jLabel18.setText("Modelo:");

		jLabel19.setText("Cor:");

		CadastroEmail.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CadastroEmailActionPerformed(evt);
			}
		});

		jLabel20.setText("Placa:");

		BotaoVoltar.setText("Voltar");
		BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BotaoVoltarActionPerformed(evt);
			}
		});

		BotaoCadastrar.setText("Cadastrar");
		BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					BotaoCadastrarActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel1.setText("Email do Proprietario");

		CadastroPlaca.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CadastroPlacaActionPerformed(evt);
			}
		});

		BotaoCadastrarProprietario.setText("Novo Proprietario");
		BotaoCadastrarProprietario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BotaoCadastrarProprietarioActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
						.addComponent(CadastroPlaca)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel19).addComponent(jLabel18).addComponent(jLabel17)
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(CadastroCor, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(CadastroModelo, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(CadastroMarca, javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout
												.createSequentialGroup()
												.addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 98,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(BotaoCadastrarProprietario).addGap(5, 5, 5)
												.addComponent(BotaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE,
														112, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(CadastroEmail, javax.swing.GroupLayout.Alignment.LEADING))
								.addComponent(jLabel1)))
						.addContainerGap(20, Short.MAX_VALUE)));

		jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { BotaoCadastrar, BotaoVoltar });

		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(CadastroCor, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel18)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(CadastroModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(CadastroMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(CadastroPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(CadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(BotaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(BotaoCadastrarProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 51,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));

		jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL,
				new java.awt.Component[] { BotaoCadastrar, BotaoVoltar });

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void CadastroCorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CadastroCorActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_CadastroCorActionPerformed

	private void CadastroModeloActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CadastroModeloActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_CadastroModeloActionPerformed

	private void CadastroMarcaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CadastroMarcaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_CadastroMarcaActionPerformed

	private void CadastroPlacaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CadastroPlacaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_CadastroPlacaActionPerformed

	private void CadastroPlaca1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CadastroPlaca1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_CadastroPlaca1ActionPerformed

	private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotaoVoltarActionPerformed
		Menu menu = new Menu();
		menu.setVisible(true);
		dispose();
	}// GEN-LAST:event_BotaoVoltarActionPerformed

	private void CadastroEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CadastroEmailActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_CadastroEmailActionPerformed

	private void BotaoCadastrarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotaoCadastrarProprietarioActionPerformed
		CadastrarProprietario tela = new CadastrarProprietario();
		tela.setVisible(true);
		dispose();
	}// GEN-LAST:event_BotaoCadastrarProprietarioActionPerformed

	private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
		listap = ex.importarProprietario(listap);
		listav = ex.importarVeiculo(listav);
		listaM = ex.importarMarcasCadastradas(listaM);

		boolean flag = true;
		boolean flag1 = true;
		boolean flag2 = true;

		if (!CadastroCor.getText().equals("") && !CadastroEmail.getText().equals("")
				&& !CadastroPlaca.getText().equals("") && !CadastroModelo.getText().equals("")
				&& !CadastroMarca.getText().equals("")) {

			String[] placa = CadastroPlaca.getText().split("");

			if (placa.length == 7 && placa[0].matches("[A-Z]") && placa[1].matches("[A-Z]") && placa[2].matches("[A-Z]")
					&& placa[3].matches("[0-9]") && placa[4].matches("[0-9]") && placa[5].matches("[0-9]")
					&& placa[6].matches("[0-9]")) {
				for (Proprietario proprietario : listap) {
					for (Veiculo veiculo : listav) {
						if (veiculo.getPlaca().equals(CadastroPlaca.getText())) {
							flag = false;
							flag1 = false;
							JOptionPane.showMessageDialog(null, "Erro: Veiculo ja cadastrado");
						}
					}
					if (proprietario.getEmail().equals(CadastroEmail.getText()) && flag1) {
						MarcasCadastradas marcaC = new MarcasCadastradas();

						veiculo.setCor(CadastroCor.getText());
						veiculo.setPlaca(CadastroPlaca.getText());
						marca.setDesc(CadastroMarca.getText());
						modelo.setDesc(CadastroModelo.getText());
						modelo.setMarca(marca);
						veiculo.setModelo(modelo);
						veiculo.setProprietario(proprietario);
						listav.add(veiculo);
						ex.exportarVeiculo(listav);

						if (listaM.size() == 0) {
							marcaC.setMarca(marca);
							marcaC.setContador(1);
							listaM.add(marcaC);

						} else {
							for (MarcasCadastradas marcas : listaM) {
								if (veiculo.getModelo().getMarca().getDesc().equals(marcas.getMarca().getDesc())) {
									marcas.setContador(marcas.getContador() + 1);
									flag2 = false;
									break;
								}
							}
							if (flag2) {
								marcaC.setMarca(marca);
								marcaC.setContador(1);
								listaM.add(marcaC);
							}
						}
						ex.exportarMarcasCadastradas(listaM);
						veiculo = new Veiculo();

						CadastroCor.setText("");
						CadastroPlaca.setText("");
						CadastroMarca.setText("");
						CadastroModelo.setText("");
						CadastroEmail.setText("");
						JOptionPane.showMessageDialog(null, "Veiculo cadastrado com sucesso!");
						flag = false;

					}
				}
				if (flag) {
					JOptionPane.showMessageDialog(null, "Proprietario nao encontrado");
				}
			} else {
				JOptionPane.showMessageDialog(null, "Placa Invalida");
			}

		} else {
			JOptionPane.showMessageDialog(null, "Dados Incompletos");
		}
	}

	/**
	 * @param args the command line arguments
	 * @throws IOException
	 */

	public static void main(String args[]) throws IOException {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CadastrarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CadastrarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CadastrarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CadastrarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CadastrarVeiculo().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BotaoCadastrar;
	private javax.swing.JButton BotaoCadastrarProprietario;
	private javax.swing.JButton BotaoVoltar;
	private javax.swing.JTextField CadastroCor;
	private javax.swing.JTextField CadastroEmail;
	private javax.swing.JTextField CadastroMarca;
	private javax.swing.JTextField CadastroModelo;
	private javax.swing.JTextField CadastroPlaca;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables
}
