/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Scanner;

import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.JobName;
import javax.print.attribute.standard.MediaSizeName;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JOptionPane;

/**
 *
 * @author Venrar
 */
public class EntradaSaida extends javax.swing.JFrame {

	private Login email = new Login();
	private ExportarImportar ex = new ExportarImportar();
	private List<Veiculo> listave = new ArrayList<Veiculo>();
	private List<Vaga> listava = new ArrayList<Vaga>();
	private List<VeiculosEstacionados> lista = new ArrayList<VeiculosEstacionados>();
	private List<Valor> listaVal = new ArrayList<Valor>();
	private List<Funcionario> listaF = new ArrayList<Funcionario>();
	private List<ProprietarioFrequente> listaP = new ArrayList<ProprietarioFrequente>();
	private List<Preco> listaPreco = new ArrayList<Preco>();

	protected VeiculosEstacionados veiculoEstacionado;
	protected Veiculo veiculo;
	protected Funcionario funcionario_1;
	protected Funcionario funcionario_2;
	protected Valor valor;
	protected Preco preco;
	private Date horarioEntrada;
	private Date horarioSaida;
	private int numeracaoVaga;
	private SimpleDateFormat date;

	/**
	 * Creates new form EntradaSaida
	 */
	public EntradaSaida() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		BotaoVoltar = new javax.swing.JButton();
		BotaoLeituraCodigoBarra = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		BotaoVoltar.setText("Voltar");
		BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BotaoVoltarActionPerformed(evt);
			}
		});

		BotaoLeituraCodigoBarra.setText("Leitura de Codigo de Barras");
		BotaoLeituraCodigoBarra.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					BotaoLeituraCodigoBarraActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(BotaoLeituraCodigoBarra,
								javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addGap(46, 46, 46).addComponent(BotaoVoltar,
								javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(BotaoLeituraCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {
		Menu menu1 = new Menu();
		menu1.setVisible(true);
		dispose();
	}

	private void BotaoLeituraCodigoBarraActionPerformed(java.awt.event.ActionEvent evt) throws IOException {

		SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy - HH:mm");
		this.date = date;
		listave = ex.importarVeiculo(listave);
		listava = ex.importarVagas(listava);
		lista = ex.importarVeiculosEstacionados(lista);
		listaVal = ex.importarValores(listaVal);
		listaP = ex.importarProprietarioFrequente(listaP);
		listaPreco = ex.importarPreco(listaPreco);
		listaF = ex.importarFuncionario(listaF);

		preco = new Preco();

		Scanner read = new Scanner(System.in);
		boolean veiculoRegistrado = false;
		boolean entrada = true;
		boolean vagaEncontrada = false;
		boolean fimVaga = true;
		boolean flag2 = true;

		String teste = JOptionPane.showInputDialog("Insira a placa");

		for (Veiculo veiculo : listave) {
			if (veiculo.getPlaca().equals(teste)) {
				for (Vaga vaga : listava) {
					if (vaga.getOcupado().equals(teste)) {
						entrada = false;
					}
				}
				if (entrada) {
					for (Vaga vaga : listava) {
						if (!vagaEncontrada) {
							if (vaga.getOcupado().equals("Livre") && !vaga.isReservada()) {
								vaga.setOcupado(teste);
								ex.exportarVagas(listava);
								vagaEncontrada = true;
								numeracaoVaga = vaga.getNumeracao();
								fimVaga = false;
							}
						}
					}

					if (!fimVaga) {

						ProprietarioFrequente propFreq = new ProprietarioFrequente();

						horarioEntrada = new Date();
						veiculoEstacionado = new VeiculosEstacionados();
						for (Funcionario funcionario : listaF) {
							if (funcionario.getEmail().equals(email.emailfunc())) {
								veiculoEstacionado.setFuncionario(funcionario);
							}
						}
						veiculoEstacionado.setHorarioEntrada(horarioEntrada);
						veiculoEstacionado.setNumeracaoVaga(numeracaoVaga);
						veiculoEstacionado.setVeiculo(veiculo);
						lista.add(veiculoEstacionado);
						ex.exportarVeiculosEstacionados(lista);

						if (listaP.size() == 0) {
							propFreq.setProprietario(veiculo.getProprietario());
							;
							propFreq.setContagem(1);
							listaP.add(propFreq);

						} else {
							for (ProprietarioFrequente prop : listaP) {
								if (veiculo.getProprietario().getEmail().equals(prop.getProprietario().getEmail())) {
									prop.setContagem(prop.getContagem() + 1);
									flag2 = false;
									break;
								}
							}
							if (flag2) {
								propFreq.setProprietario(veiculoEstacionado.getVeiculo().getProprietario());
								;
								propFreq.setContagem(1);
								listaP.add(propFreq);
							}
						}
						ex.exportarProprietarioFrequente(listaP);

						JOptionPane.showMessageDialog(null, "Entrada De Veiculo");

						imprimirTicketEntrada(veiculo, veiculoEstacionado.getNumeracaoVaga(),
								veiculoEstacionado.getFuncionario());

					} else {
						JOptionPane.showMessageDialog(null, "Sem Vagas Disponiveis");
					}

				} else {

					for (VeiculosEstacionados veiculos : lista) {
						if (veiculo.getPlaca().equals(veiculos.getVeiculo().getPlaca())) {

							veiculoEstacionado = veiculos;
							for (Vaga vaga : listava) {
								if (vaga.getOcupado().equals(veiculo.getPlaca())) {
									vaga.setOcupado("Livre");
									ex.exportarVagas(listava);
								}

								for (Valor valor : listaVal) {
									if (valor.getCodigo() == listaVal.size() - 1) {
										this.valor = valor;
									}
								}
								for (Funcionario funcionario : listaF) {
									if (funcionario.getEmail().equals(email.emailfunc())) {

									}
								}
							}
						}
					}
					horarioSaida = new Date();

					veiculoEstacionado.getHorarioEntrada();
					veiculoEstacionado.getVeiculo().getProprietario();
					veiculoEstacionado.getVeiculo();
					veiculoEstacionado.getFuncionario();
					veiculoEstacionado.getNumeracaoVaga();

					double valor = ((horarioSaida.getTime() - veiculoEstacionado.getHorarioEntrada().getTime())
							* (listaVal.get(listaVal.size() - 1).getValor()) / 3600000);
					preco.setValor(valor);
					preco.setData(horarioSaida);
					listaPreco.add(preco);
					ex.exportarPreco(listaPreco);

					JOptionPane.showMessageDialog(null, "Saida de veiculo");

					imprimirTicketSaida(veiculoEstacionado, veiculoEstacionado.getNumeracaoVaga(), horarioSaida,
							email.nomefunc(), valor);

					lista.remove(veiculoEstacionado);
					ex.exportarVeiculosEstacionados(lista);

				}

				veiculoRegistrado = true;

			}
		}
		if (!veiculoRegistrado) {
			JOptionPane.showMessageDialog(null, "Veiculo nao registrado");
			CadastrarVeiculo tela = new CadastrarVeiculo();
			tela.setVisible(true);
			dispose();
		}

	}

	/**
	 * @param args the command line arguments
	 */

	public void imprimir(String texto) {

		InputStream prin = new ByteArrayInputStream(texto.getBytes());

		DocFlavor docFlavor = DocFlavor.INPUT_STREAM.AUTOSENSE;

		SimpleDoc documentoTexto = new SimpleDoc(prin, docFlavor, null);

		PrintService impressora = PrintServiceLookup.lookupDefaultPrintService();

		PrintRequestAttributeSet printerAttributes = new HashPrintRequestAttributeSet();
		printerAttributes.add(new JobName("Impressao", null));
		printerAttributes.add(OrientationRequested.PORTRAIT);
		printerAttributes.add(MediaSizeName.ISO_A4);

		DocPrintJob printJob = impressora.createPrintJob();

		try {

			printJob.print(documentoTexto, (PrintRequestAttributeSet) printerAttributes);
		} catch (PrintException e) {
			JOptionPane.showMessageDialog(null, "Não foi possível imprimir", "Erro", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void imprimirTicketEntrada(Veiculo veiculo, int vagaEstacionamento, Funcionario funcionario) {

		Date dia = new Date();
		String data = date.format(dia);

		String imprimir;

		imprimir = ("    ESTACIONAMENTO - TICKET DE ENTRADA \n\r" + "------------------------------------- \n\r"
				+ "HORARIO ENTRADA : " + data + "\n\r" + "PROPRIETARIO " + veiculo.getProprietario().getNome() + "\n\r"
				+ "PLACA " + veiculo.getPlaca() + "\n\r" + "MODELO " + veiculo.getModelo().getDesc() + "\n\r" + "MARCA "
				+ veiculo.getModelo().getMarca().getDesc() + "\n\r" + "COR " + veiculo.getCor() + "\n\r" + "VAGA "
				+ vagaEstacionamento + "\n\r" + "FUNCIONARIO RESPONSAVEL " + funcionario.getNome() + "\n\r " + "\n\r"
				+ "\n\r" + "\n\r" + "\n\r" + "\n\r" + "\n\r" + "\n\r" + "\n\r" + "\n\r" + "" + "\f");

		imprimir(imprimir);
	}

	public void imprimirTicketSaida(VeiculosEstacionados veiculo, int vagaEstacionamento, Date hora, String funcionario,
			double valor) {

		String imprimir;
		DecimalFormat fmt = new DecimalFormat("0.00");

		imprimir = ("    ESTACIONAMENTO - TICKET DE SAIDA \n\r" + "------------------------------------- \n\r"
				+ "HORARIO ENTRADA : " + date.format(veiculo.getHorarioEntrada()) + "\n\r" + "HORARIO SAIDA : "
				+ date.format(hora) + "\n\r" + "PROPRIETARIO " + veiculo.getVeiculo().getProprietario().getNome()
				+ "\n\r" + "PLACA " + veiculo.getVeiculo().getPlaca() + "\n\r" + "MODELO "
				+ veiculo.getVeiculo().getModelo().getDesc() + "\n\r" + "MARCA "
				+ veiculo.getVeiculo().getModelo().getMarca().getDesc() + "\n\r" + "COR "
				+ veiculo.getVeiculo().getCor() + "\n\r" + "NUMERO VAGA " + vagaEstacionamento + "\n\r"
				+ "FUNCIONARIO ENTRADA " + veiculo.getFuncionario().getNome() + "\n\r " + "FUNCIONARIO SAIDA "
				+ funcionario + "\n\r" + "VALOR A PAGAR " + fmt.format(valor) + "R$" + "\n\r" + "\n\r" + "\n\r" + "\n\r"
				+ "\n\r" + "\n\r" + "\n\r" + "\n\r" + "\n\r" + "" + "\f");

		imprimir(imprimir);

	}

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EntradaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EntradaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EntradaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EntradaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new EntradaSaida().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BotaoLeituraCodigoBarra;
	private javax.swing.JButton BotaoVoltar;
	// End of variables declaration//GEN-END:variables
}
