/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento;

import java.io.IOException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.List;

public class Relatorios extends javax.swing.JFrame {

	private Html html = new Html();
	private List<MarcasCadastradas> ListaMarcasCadastradas = new ArrayList<MarcasCadastradas>();
	private ExportarImportar ex = new ExportarImportar();
	private List<ProprietarioFrequente> listaProprietariosFrequentes = new ArrayList<ProprietarioFrequente>();
	private List<Preco> listaPrecos = new ArrayList<Preco>();

	public Relatorios() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		BotaoVoltar = new javax.swing.JButton();
		BotaoFaturamentoMensal = new javax.swing.JButton();
		BotaoFaturamentoDiario = new javax.swing.JButton();
		BotaoMarcasDeVeiculos = new javax.swing.JButton();
		BotaoClientesMaisFrequentes = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		Texto = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		BotaoVoltar.setText("Voltar");
		BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BotaoVoltarActionPerformed(evt);
			}
		});

		BotaoFaturamentoMensal.setText("Faturamento Men.");
		BotaoFaturamentoMensal.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					BotaoFaturamentoMensalActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		BotaoFaturamentoDiario.setText("Faturamento Diario");
		BotaoFaturamentoDiario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					BotaoFaturamentoDiarioActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		BotaoMarcasDeVeiculos.setText("Marcas de Veiculos");
		BotaoMarcasDeVeiculos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					BotaoMarcasDeVeiculosActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		BotaoClientesMaisFrequentes.setText("Clientes Mais Freq.");
		BotaoClientesMaisFrequentes.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					BotaoClientesMaisFrequentesActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		Texto.setColumns(20);
		Texto.setRows(5);
		jScrollPane1.setViewportView(Texto);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(BotaoClientesMaisFrequentes, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(BotaoMarcasDeVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(BotaoFaturamentoDiario, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(BotaoFaturamentoMensal, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(BotaoVoltar, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jScrollPane1)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
										.createSequentialGroup()
										.addComponent(BotaoClientesMaisFrequentes,
												javax.swing.GroupLayout.PREFERRED_SIZE, 44,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(BotaoMarcasDeVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(BotaoFaturamentoDiario, javax.swing.GroupLayout.PREFERRED_SIZE,
												51, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(BotaoFaturamentoMensal, javax.swing.GroupLayout.PREFERRED_SIZE,
												45, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));

		jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL,
				new java.awt.Component[] { BotaoClientesMaisFrequentes, BotaoFaturamentoDiario, BotaoFaturamentoMensal,
						BotaoMarcasDeVeiculos, BotaoVoltar });

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotaoVoltarActionPerformed
		Menu tela = new Menu();
		tela.setVisible(true);
		dispose();

	}

	private void BotaoFaturamentoMensalActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_BotaoFaturamentoMensalActionPerformed
		SimpleDateFormat dh = new SimpleDateFormat("MM/yyyy");
		listaPrecos = ex.importarPreco(listaPrecos);
		DecimalFormat fmt = new DecimalFormat("0.00");

		html.listarHTMLFaturamentoMensal();

		Texto.setText("");
		int j = 1;
		double valor = listaPrecos.get(0).getValor();
		Calendar c = Calendar.getInstance();
		Calendar c1 = Calendar.getInstance();

		if (listaPrecos.size() == 1) {
			Texto.setText(fmt.format(valor) + "R$   " + dh.format(listaPrecos.get(0).getData()) + "\n");
		} else {
			for (int k = 0; k < listaPrecos.size() - 1; k++) {
				c.setTime(listaPrecos.get(k).getData());
				c1.setTime(listaPrecos.get(j).getData());

				if (c.get(Calendar.MONTH) == c1.get(Calendar.MONTH)) {
					valor += listaPrecos.get(j).getValor();
				} else {
					Texto.setText(Texto.getText() + fmt.format(valor) + "R$   "
							+ dh.format(listaPrecos.get(k).getData()) + "\n");
					valor = listaPrecos.get(j).getValor();
				}

				if (k == listaPrecos.size() - 2) {
					Texto.setText(Texto.getText() + fmt.format(valor) + "R$   "
							+ dh.format(listaPrecos.get(j).getData()) + "\n");
				}
				j++;
			}
		}

	}

	private void BotaoFaturamentoDiarioActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_BotaoFaturamentoDiarioActionPerformed
		SimpleDateFormat dh = new SimpleDateFormat("dd/MM/yyyy");
		listaPrecos = ex.importarPreco(listaPrecos);
		DecimalFormat fmt = new DecimalFormat("0.00");

		html.listarHTMLFaturamentoDiario();

		Texto.setText("");
		int j = 1;
		double valor = listaPrecos.get(0).getValor();
		Calendar c = Calendar.getInstance();
		Calendar c1 = Calendar.getInstance();

		if (listaPrecos.size() == 1) {
			Texto.setText(fmt.format(valor) + "R$   " + dh.format(listaPrecos.get(0).getData()) + "\n");
		} else {
			for (int k = 0; k < listaPrecos.size() - 1; k++) {
				c.setTime(listaPrecos.get(k).getData());
				c1.setTime(listaPrecos.get(j).getData());

				if (c.get(Calendar.DAY_OF_YEAR) == c1.get(Calendar.DAY_OF_YEAR)) {
					valor += listaPrecos.get(j).getValor();
				} else {
					Texto.setText(Texto.getText() + fmt.format(valor) + "R$   "
							+ dh.format(listaPrecos.get(k).getData()) + "\n");
					valor = listaPrecos.get(j).getValor();
				}

				if (k == listaPrecos.size() - 2) {
					Texto.setText(Texto.getText() + fmt.format(valor) + "R$   "
							+ dh.format(listaPrecos.get(j).getData()) + "\n");
				}
				j++;
			}
		}

	}

	private void BotaoMarcasDeVeiculosActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_BotaoMarcasDeVeiculosActionPerformed
		ListaMarcasCadastradas = ex.importarMarcasCadastradas(ListaMarcasCadastradas);
		html.listarHTMLMarcas();

		Texto.setText("");
		for (MarcasCadastradas marca : ListaMarcasCadastradas) {
			Texto.setText(Texto.getText() + "Marca: " + marca.getMarca().getDesc() + "     Quantidade: "
					+ marca.getContador() + "\n");
		}
	}

	private void BotaoClientesMaisFrequentesActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_BotaoClientesMaisFrequentesActionPerformed

		listaProprietariosFrequentes = ex.importarProprietarioFrequente(listaProprietariosFrequentes);
		html.listarHTMLProprietarios();
		Collections.sort(listaProprietariosFrequentes);

		Texto.setText("");
		for (ProprietarioFrequente prop : listaProprietariosFrequentes) {
			Texto.setText(Texto.getText() + "Proprietario: " + prop.getProprietario().getNome() + "     Quantidade: "
					+ prop.getContagem() + "\n");
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Relatorios().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BotaoClientesMaisFrequentes;
	private javax.swing.JButton BotaoFaturamentoDiario;
	private javax.swing.JButton BotaoFaturamentoMensal;
	private javax.swing.JButton BotaoMarcasDeVeiculos;
	private javax.swing.JButton BotaoVoltar;
	private javax.swing.JTextArea Texto;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables
}
