/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Venrar
 */
public class Vagas extends javax.swing.JFrame {

	private List<Vaga> lista = new ArrayList<Vaga>();
	private ExportarImportar ex = new ExportarImportar();
	protected Vaga vaga = new Vaga();

	/**
	 * Creates new form Vagas
	 */
	public Vagas() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		BotaoVoltar = new javax.swing.JButton();
		BotaoAdicionarVagas = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		QuantiaVagas = new javax.swing.JTextField();
		BotaoHabilitarVaga = new javax.swing.JButton();
		BotaoDesabilitarVaga = new javax.swing.JButton();
		NumeroVaga = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		BotaoChecarVaga = new javax.swing.JButton();
		BotaoLimparHistorico = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		HistoricoVaga = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		BotaoVoltar.setText("Voltar");
		BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BotaoVoltarActionPerformed(evt);
			}
		});

		BotaoAdicionarVagas.setText("Adicionar Vagas");
		BotaoAdicionarVagas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					BotaoAdicionarVagasActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel1.setText("Quantidade de Vagas:");

		QuantiaVagas.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				QuantiaVagasActionPerformed(evt);
			}
		});

		BotaoHabilitarVaga.setText("Habilitar Vaga");
		BotaoHabilitarVaga.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					BotaoHabilitarVagaActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		BotaoDesabilitarVaga.setText("Desabilitar Vaga");
		BotaoDesabilitarVaga.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					BotaoDesabilitarVagaActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jLabel3.setText("Numero da Vaga:");

		jLabel4.setText("Vagas:");

		BotaoChecarVaga.setText("Checar Vagas");
		BotaoChecarVaga.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					BotaoChecarVagaActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		BotaoLimparHistorico.setText("Limpar Historico");
		BotaoLimparHistorico.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BotaoLimparHistoricoActionPerformed(evt);
			}
		});

		HistoricoVaga.setColumns(20);
		HistoricoVaga.setRows(5);
		jScrollPane1.setViewportView(HistoricoVaga);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(BotaoVoltar, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(BotaoAdicionarVagas, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(QuantiaVagas).addComponent(jLabel3))
						.addComponent(BotaoDesabilitarVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 152,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(BotaoHabilitarVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 152,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(NumeroVaga, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(BotaoChecarVaga, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(BotaoLimparHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, 263,
										Short.MAX_VALUE)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel4).addGap(0, 0,
										Short.MAX_VALUE)))
						.addContainerGap()));

		jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { BotaoAdicionarVagas,
				BotaoDesabilitarVaga, BotaoHabilitarVaga, NumeroVaga, QuantiaVagas });

		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(16, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(jLabel4))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(NumeroVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(BotaoDesabilitarVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(BotaoHabilitarVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(QuantiaVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jScrollPane1))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(BotaoAdicionarVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(BotaoChecarVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(BotaoLimparHistorico))
						.addContainerGap()));

		jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL,
				new java.awt.Component[] { BotaoDesabilitarVaga, BotaoHabilitarVaga });

		jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL,
				new java.awt.Component[] { BotaoLimparHistorico, BotaoVoltar });

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {
		Menu tela = new Menu();
		tela.setVisible(true);
		dispose();
	}

	private void QuantiaVagasActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void BotaoDesabilitarVagaActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
		lista = ex.importarVagas(lista);

		boolean flag = true;

		try {
			for (Vaga vaga : lista) {
				if (vaga.getNumeracao() == Double.parseDouble(NumeroVaga.getText())) {
					vaga.setReservada(true);
					ex.exportarVagas(lista);
					flag = false;
				}
			}

			if (flag) {
				JOptionPane.showMessageDialog(null, "Vaga nao encontrada");
			}

		} catch (java.lang.NumberFormatException e) {

			JOptionPane.showMessageDialog(null, "Numero Invalido");
			QuantiaVagas.setText("");
		}

	}

	private void BotaoHabilitarVagaActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
		lista = ex.importarVagas(lista);

		boolean flag = true;
		try {
			for (Vaga vaga : lista) {
				if (vaga.getNumeracao() == Double.parseDouble(NumeroVaga.getText())) {
					vaga.setReservada(false);
					ex.exportarVagas(lista);
					flag = false;
				}
			}

			if (flag) {
				JOptionPane.showMessageDialog(null, "Vaga nao encontrada");
			}

		} catch (java.lang.NumberFormatException e) {

			JOptionPane.showMessageDialog(null, "Numero Invalido");
			QuantiaVagas.setText("");
		}

	}

	private void BotaoAdicionarVagasActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
		lista = ex.importarVagas(lista);

		try {
			double quantia = Double.parseDouble(QuantiaVagas.getText());
			for (int k = 0; k < quantia; k++) {
				vaga.setNumeracao(lista.size() + 1);
				vaga.setOcupado("Livre");
				vaga.setReservada(false);
				lista.add(vaga);
				vaga = new Vaga();
			}
			ex.exportarVagas(lista);

		} catch (java.lang.NumberFormatException e) {

			JOptionPane.showMessageDialog(null, "Numero Invalido");
			QuantiaVagas.setText("");
		}
	}

	private void BotaoChecarVagaActionPerformed(java.awt.event.ActionEvent evt) throws IOException {

		lista = ex.importarVagas(lista);
		String reservado;

		HistoricoVaga.setText("");
		for (Vaga vaga : lista) {

			if (vaga.isReservada()) {
				reservado = "Reservada";
			} else {
				reservado = "Pública";
			}
			HistoricoVaga.setText(HistoricoVaga.getText() + vaga.getNumeracao() + "  -  " + vaga.getOcupado() + "  -  "
					+ reservado + "\n");
		}

	}

	private void BotaoLimparHistoricoActionPerformed(java.awt.event.ActionEvent evt) {

		HistoricoVaga.setText("");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Vagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Vagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Vagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Vagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Vagas().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BotaoAdicionarVagas;
	private javax.swing.JButton BotaoChecarVaga;
	private javax.swing.JButton BotaoDesabilitarVaga;
	private javax.swing.JButton BotaoHabilitarVaga;
	private javax.swing.JButton BotaoLimparHistorico;
	private javax.swing.JButton BotaoVoltar;
	private javax.swing.JTextArea HistoricoVaga;
	private javax.swing.JTextField NumeroVaga;
	private javax.swing.JTextField QuantiaVagas;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables
}
